### ISSUE TITLE
Attributes of a class is not scanned.

### ISSUE THREAD

**Issue by blueset** [KristoforMaynard/SublimeAutoDocstring#1]
Attributes of a class is not scanned. Will you add the function in the future?

**Comment by KristoforMaynard** [comment]
I do intend to add this feature, but I most likely will not have time to get to it in the near future. Pull requests are certainly encouraged :). I pushed a feature branch for this called `scan_attributes` with some preliminary pieces in place. Actually scanning a class for its attributes is the task that remains to be completed. There are some TODO comments in `autodocstring.parse_class_attributes` that describe my current thoughts.

**Comment by KristoforMaynard** [comment]
This feature should now work by default in version 0.3.0.
