### ISSUE TITLE
Add to Sublime Package Control

### ISSUE THREAD

**Issue by patillacode** [KristoforMaynard/SublimeAutoDocstring#10]
Hi there,

any chance you could add this to the sublime package control for easy installation and more visibility?

Cheers!

**Comment by KristoforMaynard** [comment]
It already is :)

https://packagecontrol.io/packages/AutoDocstring

**Comment by patillacode** [comment]
It doesn't appear in the control package manager 'install package' option , I had to checkout the repo.

Thanks anyway!
