### ISSUE TITLE
Append versus insert docstring - 

### ISSUE THREAD

**Issue by jdwestbrook** [KristoforMaynard/SublimeAutoDocstring#12]
In processing legacy code modules with existing docstrings, 
is there a configuration option that will append the autogenerated 
docstring template to the text of the existing docstring rather
than inserting the template as a separate string?

**Comment by KristoforMaynard** [comment]
Interesting, this is a use case that I hadn't considered. This feature doesn't exist, but easily could. I'm thinking maybe a separate command in the command pallet would be the most natural way to access a feature like this.

**Comment by jdwestbrook** [comment]
If this accessible from a "user preference" for the Sublime text plugin that would be
very helpful.

**Comment by KristoforMaynard** [comment]
As of version 0.4.0, this option exists as "keep_previous".

**Comment by jdwestbrook** [comment]
Brilliant --  Thanks very much for adding this option -
