### ISSUE TITLE
start_with_newline is ignored when updating a docstring.

### ISSUE THREAD

**Issue by olafSmits** [KristoforMaynard/SublimeAutoDocstring#13]
Suppose I define a function

```
def f():
    pass
```

In my settings I have  "start_with_newline": true and I'm using numpy style. Next I apply the ctrl+alt+'  command and it generates a docstring:

```
def f():
    """
    Summary

    Returns
    -------
    name : TYPE
        Description
    """
    pass
```

If I now apply ctrl+alt+'  again I'm effectively updating the docstring, but since nothing has changed this action should not do anything.. However, this update removes the newline character at the start of the summary, as I get:

```
def f():
    """Summary

    Returns
    -------
    name : TYPE
        Description
    """
   pass
```

So it seems like the docstring update is ignoring the "start_with_newline" setting.

**Comment by KristoforMaynard** [comment]
Fixed in version 0.4.0.
