### ISSUE TITLE
Returns section not being inserted on existing docstrings

### ISSUE THREAD

**Issue by montegoode** [KristoforMaynard/SublimeAutoDocstring#15]
I found your plugin today while working on documenting an existing project. Great stuff and I can't wait to use it plus napoleon in the future.

The issue that I'm having is that when I update an existing doctoring, it will not insert a Returns section. It will only do that when creating a completely fresh docstring for a method. I looked at the configuration options and some of the source as well and didn't see that I was missing something I could toggle on.

This happens on existing docstrings that just contain text comments, and ones that already have RST-style param/return markup in them.

Is there some way to enable inserting the Returns section on an existing docstring?

**Comment by montegoode** [comment]
For what it's worth, I modified the following in auto_docstring.py: 

```
            # prepare return name/type for new / updated returns section
            if is_new and name != "__init__":
                ret_name = default_return_name
                ret_type = ret_ano if ret_ano else default_type
            else:
                ret_name = default_return_name
                ret_type = ret_ano if ret_ano else default_type   # changed this line
```

And it will now insert a Returns section on an existing docstring.

**Comment by KristoforMaynard** [comment]
Yup, that's exactly what I would do :) This sounds like a useful feature if you want to add a flag to the settings and submit a PR. The only thing that I would want to make sure is that if there is a pre-existing docstring, it should be left alone. To this end, you may need another branch that makes sure the returns section doesn't already exist before setting ret_name and ret_type.

**Comment by montegoode** [comment]
I might do that! I'm not sure if I'll have any use for that feature going forward since after I get these existing docstrings converted, I'll just be using your package for fresh docstrings in the future. :) So this hack might suffice for my immediate purposes. I'll send a pull request if I end up fleshing this feature out.

I don't know if you want to leave this issue open or not. Do feel free to close it.

Thanks for the help and the great package!
