### ISSUE TITLE
how to configure to use single quote?

### ISSUE THREAD

**Issue by pirDOL** [KristoforMaynard/SublimeAutoDocstring#16]
rt, does SublimeAutoDocstring support to configure single quote & double quote? thx

**Comment by KristoforMaynard** [comment]
My bad, it appears this is an option, but it's not documented. The option is called "default_qstyle", so you can add something like this to your settings:

```
`"default_qstyle": "'''"`
```

I'm leaving this issue open to remind myself to document this setting :)

**Comment by pirDOL** [comment]
i've tried and default_qstyle option worked, thx
