### ISSUE TITLE
Support async def

### ISSUE THREAD

**Issue by sametmax** [KristoforMaynard/SublimeAutoDocstring#17]
If you use asyncio, the plugin does not detect when you are on a function signature with async.

**Comment by KristoforMaynard** [comment]
I need more specifics to understand this issue.

**Comment by sametmax** [comment]
If you do:

```
async def foo(self):
```

You can't use autodocstring on this method, it will create the docstring on the class.

**Comment by KristoforMaynard** [comment]
I see - I was unaware of the new async/await syntax. This is twice that you've educated me about a new python feature 😄 . This should now be fixed with version 0.5.1

**Comment by sametmax** [comment]
I'm a Python trainer for a living :) Thanks for this awesome tool, works like a charm now.
