### ISSUE TITLE
Keyboard Shortcut not working with german keyboard

### ISSUE THREAD

**Issue by maltesa** [KristoforMaynard/SublimeAutoDocstring#18]
It would be nice if it is easier to change the shortcut (e.g. via the package menu) for generating the docstring, since the shortcut uses a ' which is shift+# on a german keyboard.

**Comment by KristoforMaynard** [comment]
Are these menu shortcuts something like you are thinking about?

**Comment by maltesa** [comment]
yes perfect! thank you

**Comment by KrisKorrel** [comment]
Am i right in that this only works for OSX? I have to manually open and edit the Linux file to change my keybinding.

**Comment by KristoforMaynard** [comment]
Oops - let me know if version 0.5.8 works for you. I don't have time to spin up a VM at the moment.

**Comment by KrisKorrel** [comment]
That was quick! But yeah seems to work. Thanks!
I had to manually install "0.5.8" from Github though. But I assume that is what you meant.
