### ISSUE TITLE
PEP 257 (D400) - First line must end with period.

### ISSUE THREAD

**Issue by aprendacodigo** [KristoforMaynard/SublimeAutoDocstring#2]
Got "Summary" instead of "Summary."

**Comment by KristoforMaynard** [comment]
I'm not sure how I feel about adding a period to the filler text to conform to the PEP. My reasoning is that the whole line should be replaced with useful text anyway, and having one word without punctuation makes it possible to just double click on "Summary" to select the whole line. There is a point that the period should be there regardless, but I'm the sort of person that would automatically type the period and be annoyed having to delete it.

I would accept a PR making it an option, or better yet, letting the user set their own filler text.

**Comment by aprendacodigo** [comment]
Sure, I can fork and PR. Where I can find the placeholder code? (docstring_styles.py?)

**Comment by KristoforMaynard** [comment]
All the placeholder text can be set in the settings as of version 0.3.2. The Option for the summary text is `default_summary`.
