### ISSUE TITLE
bug in parse_return_keyword() ?

### ISSUE THREAD

**Issue by beepbap** [KristoforMaynard/SublimeAutoDocstring#20]
Hi,
there is a bug with parsing functions/methods without a return statement that came up recently. If you try to generate a doc string for something like this (including the faulty doc string output):
```python
def __init__(self, name):
        # buggy output, status bar tells me that the package is confused ;)
        """<FRESHLY_INSERTED>"""
        super().__init__(name='{0}_dict'.format(name))
````
the package will trip and return:
> File "auto_docstring in ...\Sublime Text 3\Installed Packages\AutoDocstring.sublime-package", line 572, in parse_return_keyword
> IndexError: list index out of range

If you include an explicit `return None`
```python
def __init__(self, name):
        """
        
        Args:
            name (TYPE): Description
        """
        super().__init__(name='{0}_dict'.format(name))
        return None
```
it will parse fine.

Cheers

**Comment by KristoforMaynard** [comment]
Thanks for letting me know about this!

**Comment by beepbap** [comment]
Hey, thanks for the quick fix! I did notice one thing though. While in earlier versions the plugin did create doc strings without a _returns_ statement for functions/methods that did not contain the `return` keyword the current version seems to always include such statement.

Deleting such statement by hand is merely an inconvenience but I would prefer the old behaviour if it would not cause too much trouble. I am not sure how much this does branch into the whole discussion whether writing python methods that do not include an explicit `return` statement is a good idea in the first place.

**Comment by KristoforMaynard** [comment]
So, I'm of the opinion that the docs should tell you what you get back, but I also think that a tool like this plugin should have minimal negative impact on a developer's workflow. I imagine going back to the old behavior via a flag in the settings is appropriate. I can add this when I get a free moment :)
