### ISSUE TITLE
Error with get_whole_block() and tabulation

### ISSUE THREAD

**Issue by syffer** [KristoforMaynard/SublimeAutoDocstring#28]
It seems that the function get_whole_block() doesn't work when a tabulation is used as indent.

The function get_whole_block() returns only the first line (the definition line) when it is the case. 
As a consequence, Returns and Exceptions sections aren't parsed correctly.

```
def test(a, e): 
	return 4
	raise Exception
```

**Comment by KristoforMaynard** [comment]
This could be due to a rogue raw string at auto_docstring.py:L328. I'll test this when I get a chance.
