### ISSUE TITLE
Option to allow the docstring to start with a newline

### ISSUE THREAD

**Issue by aldanor** [KristoforMaynard/SublimeAutoDocstring#4]
This is a valid numpy-style docstring and often times this style is preferred:

``` python
"""
Summary.

<...>
"""
```

Would it be possible to have a "start_with_newline" option?

**Comment by KristoforMaynard** [comment]
I committed a `start_with_newline` option. I'd just like test it a bit more before tagging it as a release.

**Comment by KristoforMaynard** [comment]
This option is now available in version 0.3.2.

**Comment by aldanor** [comment]
That's great, thanks!
