### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by mattdornfeld** [KristoforMaynard/SublimeAutoDocstring#46]

**Comment by Hack-Hut** [comment]
Sublime -> preference -> browse packages 
This will open your package storage location, just drop the unzipped "sublimeAutoDocstring" package in that folder then you're done.

**Comment by KristoforMaynard** [comment]
Fair enough. I added some install instructions to the ``README.md``. Thanks @Hack-Hut for reminding me that plugins can be installed without package control.
