### ISSUE TITLE
Feature request: Make this executable as a command line application

### ISSUE THREAD

**Issue by mattdornfeld** [KristoforMaynard/SublimeAutoDocstring#47]
This is the best docstring generator I've seen so far, and it's currently a gap in the Python tooling space to be able to generate docstrings from the command line. How much work would it be to make this executable from a command line application?

**Comment by KristoforMaynard** [comment]
I just made a quick tour of ``auto_docstring.py`` and now I remember the degree to which the python parsing depends on ST. In short, things are wicked intertwined. The frontend actually uses MagicPython's syntax highlighting symbols to avoid doing some of the parsing itself.

For a command line frontend, it might make more sense to use something like [parso](https://github.com/davidhalter/parso) to have proper python parsing (especially for annotations). I've been wanting to try this for the ST plugin, but haven't had the time to test parso's robustness against syntax errors. I figure that a tool in the editor should always let you do what you're thinking at the moment. For instance, imagine there's a mismatched parentheses somewhere, but you're thinking about a docstring for a function further down in the file. It breaks your train of thought if you have to go fix the syntax error before you can continue.

Luckily, ``docstring_styles.py`` should work fine for the docstring parsing / formatting regardless of the frontend. After writing this response, I'm thinking a command line interface is significant enough to require its own project. I'll go ahead and close this issue, but feel free to continue the discussion if anyone wants to give this a try.

**Comment by mattdornfeld** [comment]
@KristoforMaynard Thanks for the reply! Would you be able to expand on that? Are there features in this code that are dependent on sublime text?
