### ISSUE TITLE
Support for RestructuredText

### ISSUE THREAD

**Issue by minhtuev** [KristoforMaynard/SublimeAutoDocstring#7]

**Comment by minhtuev** [comment]
How do I configure SublimeAudoDocstring with rst style?

**Comment by KristoforMaynard** [comment]
AutoDocstring doesn't currently have a general rst style. If you wish to add one, you would want to edit `docstring_styles.py` and:
1. Create a new subclass of `Section`
2. Create a new subclass of `Docstring`
3. Add the new style to the `STYLE_LOOKUP` dictionary

The existing styles in that source file can more or less be used as templates.

**Comment by KristoforMaynard** [comment]
I'm closing this issue because it's ill-defined and there appears to be no interest.
