### ISSUE TITLE
Napolean?

### ISSUE THREAD

**Issue by pkmital** [KristoforMaynard/SublimeAutoDocstring#9]
Is there/was there support for napolean?

**Comment by KristoforMaynard** [comment]
This plugin supports both Google and Numpy styled docstrings, so in that sense, yes, it does support napoleon. In the past (before I understood how napoleon works), I tried to use some of the napoleon code to parse docstrings, but it quickly became clear this was not the path of least resistance. As such, there may still be some references to napoleon in the current code, but it's little more than a name that means "both Google and Numpy."

**Comment by pkmital** [comment]
That makes sense.  Thank you for clearing that up!
